#!/bin/bash
cd
echo ""
echo "Needing file permission"
termux-setup-storage & sleep 4 &>/dev/null

while true; do
    if [ -e storage ]; then
        rm -rf /sdcard/termux-box
        break
    else
        echo "If you denied permission, turn on it by yourself"
    fi
    sleep 2
done

mkdir -p /sdcard/WinuxOS

echo ""
echo "Updating termux packages"
pkg update >/dev/null 2>&1
pkg upgrade >/dev/null 2>&1

echo ""
echo "Downloading everything we need"
clear
echo ""
echo "installing pd"
pkg install proot-distro 
clear
echo ""
echo "installing wget"
pkg install wget
echo ""
echo "installing x11"
clear
pkg install x11-repo
clear
echo ""
echo "installing x11"
pkg install termux-x11-nightly

proot-distro install debian
clear
echo ""
echo "Now run debian (pd login debian, then install git and clone this repo again and run setup-debian)"


