#!/bin/bash
cd
echo ""
echo "Needing file permission"
termux-setup-storage & sleep 4 &>/dev/null

while true; do
    if [ -e storage ]; then
        rm -rf /sdcard/termux-box
        break
    else
        echo "If you denied permission, turn on it by yourself"
    fi
    sleep 2
done

mkdir -p /sdcard/WinuxOS

echo ""
echo "Updating termux packages"
pkg update >/dev/null 2>&1
pkg upgrade >/dev/null 2>&1

echo ""
echo "Downloading all needed repo's"
pkg install proot-distro 
pkg install wget 

proot-distro install debian
